### ISSUE TITLE
Deploying any container results in error "starting container with non-empty request body was deprecated since API v1.22 and removed in v1.24"

### ISSUE THREAD

**Issue by robcav862** [hassio-addons/addon-portainer#127]
# Problem/Motivation
Deploying any container results in error "starting container with non-empty request body was deprecated since API v1.22 and removed in v1.24"
![image](https://user-images.githubusercontent.com/85896438/130290039-84466529-3d37-45f8-bb4e-d0b2411ed8a4.png)

> (Why the issue was filed)

## Expected behavior
Container deploys
> (What you expected to happen)

## Steps to reproduce
Deploy any container from the docker.io
nginxdemos/hello:latest
tutum/hello-world:latest

**Comment by LewisSpring** [comment]
Same issue here, just trying to deploy a container of an image I made with a dockerfile.

**Comment by frenck** [comment]
I will definitely take a look, however, please note, this add-on is mainly useful/meant for debugging purposes. Running additional containers on a Home Assistant OS or Supervised system is not supported by Home Assistant.

**Comment by pete-leese** [comment]
Also having the same issue here guys.

**Comment by DarkFox** [comment]
> I will definitely take a look, however, please note, this add-on is mainly useful/meant for debugging purposes. Running additional containers on a Home Assistant OS or Supervised system is not supported by Home Assistant.

This does also apply to containers installed via the add-on system. You can stop them, but can't start them again.

**Comment by frenck** [comment]
> You can stop them, but can't start them again.

You should never do such a thing in a system with a Supervisor, so for that specific issue, it is actually good.

**Comment by Depechie** [comment]
All my own created portainer docker containers have the same issue... weird fact, for example pihole I got that fixed by using a portainer Stack instead of the UI

**Comment by ncresswell** [comment]
Neil here from Portainer. We will take a look at this from our side.. this only seems to impact HASS users tho, so something specific to that deployment.

**Comment by frenck** [comment]
> All my own created portainer docker containers have the same issue.

That is not a supported scenario by Home Assistant and thus out of scope for this project and issue.

**Comment by Depechie** [comment]
@frenck would you suggest not installing portainer as add-on but directly on the OS? Running supervised ( for reference ).

**Comment by timothymarq** [comment]
Same issue here. Hassio, just installed portainer add-on and same errors 
Failure
starting container with non-empty request body was deprecated since API v1.22 and removed in v1.24

**Comment by frenck** [comment]
Please avoid posting "I have same issue" responses on GitHub, instead leave a 👍 on the initial issue description. Thanks 👍

**Comment by al3x1337** [comment]
Also having the same issue. Previously used with an older version of Hassio with no problem. Tried the EDGE version with the same error. Perhaps Hassio upgraded something in the new version that isn't compatible?

**Comment by Fox350** [comment]
@al3x1337 may I ask how did you install the previous release in HA ?  Looks like my partial portainer snapshop is scrap and unable to restore before the upgrade.  It would be useful :)  Thanks!

**Comment by welchste** [comment]
Same issue as everyone above obviously. I don't use the Portainer addon to run containers on my HASSOS supervisor or anything. I use to to manage my docker containers on other systems. So when I tried to restart and re-pull an image to my surprise like many of you I can't start it.

**Comment by al3x1337** [comment]
> @al3x1337 may I ask how did you install the previous release in HA ? Looks like my partial portainer snapshop is scrap and unable to restore before the upgrade. It would be useful :) Thanks!

https://github.com/hassio-addons/addon-portainer/releases/tag/v1.5.2
Download the source and copy the folder into Addons on Home Assistant via Samba/Vscode. 
Go to Supervisor -> Add on Store -> 3 dots in top right -> Reload and you should see at the top Portainer under Local Addons

**Comment by Fox350** [comment]
Many thanks !  I appreciate

Télécharger Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by oetken** [comment]
Same here. Just installed and fails out of the box.

**Comment by igiul667** [comment]
Had the same problem, however I tried pressing "Restart" instead of start and the container started. I don't know why it worked or if it will work for you, but try it.

**Comment by akrigator** [comment]
Faced with the issue on hassos with plex container. I've workaround it by creating the plex stack instead of a singleton container, here is the compose file for deployment:
```
version: "2.1"
services:
  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - DEBIAN_FRONTEND=noninteractive
      - GUID=0
      - HOME=/root
      - LANG=en_US.UTF-8
      - LANGUAGE=en_US.UTF-8
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - PLEX_ARCH=arm64
      - PLEX_DOWNLOAD=https://downloads.plex.tv/plex-media-server-new
      - PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR=/config/Library/Application Support
      - PLEX_MEDIA_SERVER_HOME=/usr/lib/plexmediaserver
      - PLEX_MEDIA_SERVER_INFO_DEVICE=Docker Container (LinuxServer.io)
      - PLEX_MEDIA_SERVER_INFO_VENDOR=Docker
      - PLEX_MEDIA_SERVER_MAX_PLUGIN_PROCS=6
      - PLEX_MEDIA_SERVER_USER=abc
      - PUID=0
      - TERM=xterm
      - VERSION=latest
    volumes:
      - /mnt/data/docker/volumes/plexconfig:/config
      - ds_plexscanner:/config/Library/Application Support/Plex Media Server/Scanners
      - ds_photo:/mnt/photo
      - ds_video:/mnt/video
      - ds_surveillance:/mnt/surveillance
    restart: unless-stopped
```
Where the `ds_*`  volumes are nfs shares. But a root cause is still unclear for me. 

```
 Add-on version: 2.0.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 6.2  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2021.8.8
 Home Assistant Supervisor: 2021.08.1
```

**Comment by EpicLPer** [comment]
> I will definitely take a look, however, please note, this add-on is mainly useful/meant for debugging purposes. Running additional containers on a Home Assistant OS or Supervised system is not supported by Home Assistant.

I mainly use Portainer on HASS to manage other hosts, even there it seems to happen. It also seems to be unable to "Recreate containers", it seems to just load indefinitely on Deploy which may be related to this issue.

**Comment by ncresswell** [comment]
OK, i have continued to investigate... 

I cloned the add-on repo to my machine, and built an image from it... i then started the image with the following command: _docker run -d -p 8099:8099 -v /var/run/docker.sock:/var/run/docker.sock --entrypoint /opt/portainer/portainer b26bdd27337f -p :8099_ which started fine, and i can run/start/stop containers fine.. so something in the HaaS init script is causing this issue. 

Frenck, i have emailed you directly if you want to triage this together with Portainer.

**Comment by sunib** [comment]
> I will definitely take a look, however, please note, this add-on is mainly useful/meant for debugging purposes. Running additional containers on a Home Assistant OS or Supervised system is not supported by Home Assistant.

@frenck: Could you please add this statement in the readme of the plugin? I was not aware of this also ran into problems while update my OS to version 6.1 (I'm not able to run my 2 small containers anymore). The whole portainer GUI is so nice that it just screams to be used to run simple containers. :-)

**Comment by edgarfu721** [comment]
Failure
starting container with non-empty request body was deprecated since API v1.22 and removed in v1.24

So sad for this failure.

**Comment by edgarfu721** [comment]
> # Problem/Motivation
> Deploying any container results in error "starting container with non-empty request body was deprecated since API v1.22 and removed in v1.24"
> ![image](https://user-images.githubusercontent.com/85896438/130290039-84466529-3d37-45f8-bb4e-d0b2411ed8a4.png)
> 
> > (Why the issue was filed)
> 
> ## Expected behavior
> Container deploys
> 
> > (What you expected to happen)
> 
> ## Steps to reproduce
> Deploy any container from the docker.io
> nginxdemos/hello:latest
> tutum/hello-world:latest



> I will definitely take a look, however, please note, this add-on is mainly useful/meant for debugging purposes. Running additional containers on a Home Assistant OS or Supervised system is not supported by Home Assistant.

Is it possible to develop K8S add-on?

**Comment by omayhemo** [comment]
Same problem with mine.  I updated today and now I can't start new containers.

**Comment by shupershuff** [comment]
Any updates on this? Super annoying that it doesn't work at all...

**Comment by drdownload** [comment]
Is this problem only on supervised install or also on stock hass?

**Comment by MaxWinterstein** [comment]
As mentioned by @Depechie a temporary workaround is to deploy another portainer via a stack.

> All my own created portainer docker containers have the same issue... weird fact, for example pihole I got that fixed by using a portainer Stack instead of the UI

Just head towards `Stacks`, and use this one:

```yaml
version: '2'

services:
  portainer:
    image: portainer/portainer-ce
    ports:
      - "9000:9000"
      - "8000:8000"
    volumes:
      - portainer_data2:/data
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes

volumes:
  portainer_data2:
```

The new portainer, that lives beside the other one, is available at http://homeassistant.local:9000/ 

Now I have some new portainer2 running that works just as needed, and I can deploy something. 

**Caution: Take care!**
