### ISSUE TITLE
Feature suggestion: Make edge-agent-only version of this addon

### ISSUE THREAD

**Issue by sgofferj** [hassio-addons/addon-portainer#146]
# Problem/Motivation

The addon provides a complete portainer installation on the homeassistant device which is great if the device is the only device in the network running docker. However, when there already is a portainer-orchestrated docker environment, this is somewhat of an overhead and inconvenience because it requires the admin to jump between portainer instances. It also means, that no centrally controlled edge stacks can be deployed on the homeassistant device.

## Proposed changes

I would like to propose a version of this addon which only deploys the portainer edge-agent. This way, the homeassistant device can be seamlessly integrated into an existing portainer-orchestrated infrastructure and centrally managed edge-stacks e.g. for monitoring can be deployed.

**Comment by rirofal** [comment]
Was looking for the exact same thing... 👍 

"Solved" this by first starting up this add-on and then via this Portainer deploy a stack, then you can stop this full add-on and manage the containers from another Portainer.

```
  portainer-agent:
    image: portainer/agent
    container_name: portainer-agent
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    ports:
     - 9001:9001
```
